git config --global alias.br 'branch'
git config --global alias.ci 'commit'
git config --global alias.cm 'commit -m'
git config --global alias.ca 'commit --amend'
git config --global alias.co 'checkout'
git config --global alias.cb 'checkout -b'
git config --global alias.st 'status'
git config --global user.email 'wendachu@foxmail.com'
git config --global user.name 'wind'